### ISSUE TITLE
copyright infrigement

### ISSUE THREAD

**Issue by edvincandon** [frouo/scaling-couscous#1]
Could you please delete this repo - my startup has the same name : we're helping couscous makers actually scale their industry.

**Comment by frouo** [comment]
First come first serve. Sorry.

Maybe you should consider `scaling-merguez`?

**Comment by edvincandon** [comment]
![image](https://user-images.githubusercontent.com/11134131/157936980-83c8a602-d338-4a89-ba7e-9e4efc3323e1.png)
My lawyer has been notified.

**Comment by rajivjhoomuck** [comment]
scaling-merguez is taken too, you can have scaling-merdez
